import Head from "next/head";
import "@/styles/Home.module.css";
import fs from "fs/promises";
import path from "path";
import * as React from "react";
import {
  Planet,
  PlanetContext,
  PlanetContextProps,
} from "@/utils/planet-context";
import Layout from "@/component/Layout";

interface ResponseProps {
  planets: Planet[];
  geologyImages: string[];
}

export const Home = (props: ResponseProps) => {
  const context = React.useContext<PlanetContextProps>(PlanetContext);
  const [hydrated, setHydrated] = React.useState<boolean>(false);

  React.useEffect(() => {
    if (context.currentPlanet === undefined) return;
    context.setCurrentSpec(1);
    setHydrated(true);
  }, [context]);

  React.useEffect(() => {
    if (context.planets.length > 0) return;
    context.populatePlanets(props.planets);
  }, [props.planets, context]);

  return hydrated ? (
    <>
      <Head>
        <title>Planetarium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
    </>
  ) : null;
};
export default Home;

export const getStaticProps = async () => {
  const filePath = path.join("public", "data", "data.json");
  const jsonData = await fs.readFile(filePath, "utf8");
  const data = JSON.parse(jsonData);
  return {
    props: { planets: data.planets},
  };
};