import Head from "next/head";
import styles from "@/styles/Home.module.css";
import fs from "fs/promises";
import path from "path";
import * as React from "react";
import {
  Planet,
  PlanetContext,
  PlanetContextProps,
} from "@/utils/planet-context";
import NavigationCard from "@/component/NavigationCard";

interface ResponseProps {
  planets: Planet[];
}

export const Home = (props: ResponseProps) => {
  const context = React.useContext<PlanetContextProps>(PlanetContext);
  React.useEffect(() => {
    if (context.planets.length > 0) return;
    context.populatePlanets(props.planets);
  }, [props.planets, context]);
  return (
    <>
      <Head>
        <title>Planetarium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Main Page</h1>
        <div className={"navigationMenu"}>
        {context.planets.map((value: Planet, index: number) => (
          <NavigationCard
            key={index}
            planet={value}
          />
        ))}
        </div>
      </main>
    </>
  );
};
export default Home;

export const getStaticProps = async () => {
  const filePath = path.join(process.cwd(), "data", "data.json");
  const jsonData = await fs.readFile(filePath, "utf8");
  const data = JSON.parse(jsonData);
  return {
    props: data,
  };
};
